openapi: 3.0.3
info:
  title: AI Native Platform API
  version: 0.0.1
  description: AI Native Platform
paths:
  /knowledge/namespaces/{namespace_pk}/documents/:
    get:
      operationId: knowledge_namespaces_documents_list
      description: 获取文档列表
      parameters:
      - in: path
        name: namespace_pk
        schema:
          type: string
        required: true
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - knowledge
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedKnowledgeDocumentListList'
          description: ''
    post:
      operationId: knowledge_namespaces_documents_create
      description: 创建文档
      parameters:
      - in: path
        name: namespace_pk
        schema:
          type: string
        required: true
      tags:
      - knowledge
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KnowledgeDocumentCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/KnowledgeDocumentCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/KnowledgeDocumentCreate'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KnowledgeDocumentCreate'
          description: ''
  /knowledge/namespaces/{namespace_pk}/documents/{id}/:
    get:
      operationId: knowledge_namespaces_documents_retrieve
      description: 获取文档详情
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      - in: path
        name: namespace_pk
        schema:
          type: string
        required: true
      tags:
      - knowledge
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    put:
      operationId: knowledge_namespaces_documents_update
      description: 更新文档
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      - in: path
        name: namespace_pk
        schema:
          type: string
        required: true
      tags:
      - knowledge
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: knowledge_namespaces_documents_destroy
      description: 删除文档
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      - in: path
        name: namespace_pk
        schema:
          type: string
        required: true
      tags:
      - knowledge
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    KnowledgeDocumentCreate:
      type: object
      description: 知识文档创建序列化器 - 简化的创建接口
      properties:
        title:
          type: string
          title: 标题
          description: 知识文档或文件夹的标题
          maxLength: 255
        content:
          type: string
          nullable: true
          title: 内容
          description: 知识文档的内容，支持Markdown格式
        summary:
          type: string
          nullable: true
          title: 摘要
          description: 知识文档的摘要描述
        doc_type:
          allOf:
          - $ref: '#/components/schemas/DocTypeEnum'
          title: 文档类型
          description: '文件夹、文档、工具或表单


            * `folder` - 文件夹

            * `document` - 文档

            * `tool` - 工具

            * `form` - 表单'
        status:
          allOf:
          - $ref: '#/components/schemas/StatusEnum'
          title: 状态
        parent:
          type: integer
          nullable: true
          title: 父级文档
          description: 用于构建层次结构
        sort_order:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
          title: 排序序号
          description: 在同级目录中的排序序号，数字越小排序越靠前
        is_public:
          type: boolean
          title: 是否公开
          description: 是否对知识库内所有成员公开
      required:
      - title
    PaginatedKnowledgeDocumentListList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/KnowledgeDocumentList'
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
