# Generated by Django 5.2.4 on 2025-08-01 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ASRModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模型名称")),
                ("provider", models.CharField(max_length=50, verbose_name="提供商")),
                ("model_id", models.CharField(max_length=100, verbose_name="模型ID")),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API密钥"
                    ),
                ),
                ("api_base", models.URLField(blank=True, verbose_name="API基础URL")),
                ("description", models.TextField(blank=True, verbose_name="模型描述")),
                (
                    "supported_languages",
                    models.JSONField(default=list, verbose_name="支持的语言"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asr_models_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "ASR模型",
                "verbose_name_plural": "ASR模型",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GlobalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                ("description", models.TextField(blank=True, verbose_name="配置描述")),
                (
                    "config_type",
                    models.CharField(max_length=50, verbose_name="配置类型"),
                ),
                ("config_value", models.JSONField(verbose_name="配置值")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_configs_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "全局配置",
                "verbose_name_plural": "全局配置",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模型名称")),
                ("provider", models.CharField(max_length=50, verbose_name="提供商")),
                ("model_id", models.CharField(max_length=100, verbose_name="模型ID")),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API密钥"
                    ),
                ),
                ("api_base", models.URLField(blank=True, verbose_name="API基础URL")),
                ("description", models.TextField(blank=True, verbose_name="模型描述")),
                (
                    "max_tokens",
                    models.IntegerField(default=4096, verbose_name="最大token数"),
                ),
                (
                    "temperature",
                    models.FloatField(default=0.7, verbose_name="温度参数"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_models_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM模型",
                "verbose_name_plural": "LLM模型",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RerankModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模型名称")),
                ("provider", models.CharField(max_length=50, verbose_name="提供商")),
                ("model_id", models.CharField(max_length=100, verbose_name="模型ID")),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API密钥"
                    ),
                ),
                ("api_base", models.URLField(blank=True, verbose_name="API基础URL")),
                ("description", models.TextField(blank=True, verbose_name="模型描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rerank_models_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rerank模型",
                "verbose_name_plural": "Rerank模型",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TTSModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模型名称")),
                ("provider", models.CharField(max_length=50, verbose_name="提供商")),
                ("model_id", models.CharField(max_length=100, verbose_name="模型ID")),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API密钥"
                    ),
                ),
                ("api_base", models.URLField(blank=True, verbose_name="API基础URL")),
                ("description", models.TextField(blank=True, verbose_name="模型描述")),
                (
                    "supported_languages",
                    models.JSONField(default=list, verbose_name="支持的语言"),
                ),
                (
                    "supported_voices",
                    models.JSONField(default=list, verbose_name="支持的音色"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tts_models_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "TTS模型",
                "verbose_name_plural": "TTS模型",
                "ordering": ["-created_at"],
            },
        ),
    ]
