# Generated by Django 5.2.4 on 2025-08-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GlobalConfig",
        ),
    ]
