# Generated by Django 5.2.4 on 2025-08-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0002_remove_global_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmmodel",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic"),
                    ("azure_openai", "Azure OpenAI"),
                    ("azure_ai", "Azure AI"),
                    ("google_vertexai", "Google Vertex AI"),
                    ("google_genai", "Google GenAI"),
                    ("bedrock", "AWS Bedrock"),
                    ("bedrock_converse", "AWS Bedrock Converse"),
                    ("cohere", "Cohere"),
                    ("fireworks", "Fireworks"),
                    ("together", "Together"),
                    ("mistralai", "Mistral AI"),
                    ("huggingface", "Hugging Face"),
                    ("groq", "Groq"),
                    ("ollama", "Ollama"),
                    ("google_anthropic_vertex", "Google Anthropic Vertex"),
                    ("deepseek", "DeepSeek"),
                    ("ibm", "IBM"),
                    ("nvidia", "NVIDIA"),
                    ("xai", "xAI"),
                    ("perplexity", "Perplexity"),
                ],
                max_length=50,
                verbose_name="提供商",
            ),
        ),
    ]
