# Generated by Django 5.2.4 on 2025-08-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0003_alter_llmmodel_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llmmodel",
            name="description",
        ),
        migrations.RemoveField(
            model_name="llmmodel",
            name="max_tokens",
        ),
        migrations.RemoveField(
            model_name="llmmodel",
            name="name",
        ),
        migrations.RemoveField(
            model_name="llmmodel",
            name="temperature",
        ),
        migrations.AlterField(
            model_name="llmmodel",
            name="model_id",
            field=models.CharField(max_length=100, unique=True, verbose_name="模型ID"),
        ),
    ]
