# Generated by Django 5.2.4 on 2025-08-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0004_remove_llmmodel_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rerankmodel",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="ttsmodel",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="ASRModel",
        ),
        migrations.DeleteModel(
            name="RerankModel",
        ),
        migrations.DeleteModel(
            name="TTSModel",
        ),
    ]
