# Generated by Django 5.1.6 on 2025-06-29 14:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='命名空间唯一标识（3-100字符）', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('description', models.TextField(blank=True, help_text='空间描述信息', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='目录名称（1-255字符）', max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='父目录（空表示根目录）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='directory.directory')),
                ('namespace', models.ForeignKey(help_text='所属命名空间', on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='directory.namespace')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('namespace', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='笔记标题（1-255字符）', max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('content', models.TextField(blank=True, default='', help_text='富文本内容（支持HTML）')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directory', models.ForeignKey(help_text='所属目录', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='directory.directory')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('directory', 'title')},
            },
        ),
    ]
