# Generated by Django 5.1.6 on 2025-07-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('md', 'Markdown'), ('database', 'Database'), ('tool', 'Tool')], default='md', help_text='笔记类别（md, database, tool）', max_length=50),
        ),
    ]
