apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "django-backend.fullname" . }}-media
  labels:
    {{- include "django-backend.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 