apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-backend.fullname" . }}
  labels:
    {{- include "django-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.django.service.type }}
  ports:
    - port: {{ .Values.django.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.django.service.type "NodePort") .Values.django.service.nodePort }}
      nodePort: {{ .Values.django.service.nodePort }}
      {{- end }}
  selector:
    {{- include "django-backend.selectorLabels" . | nindent 4 }}