# Generated by Django 5.2.4 on 2025-08-05 15:37

import bot.models.bot
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Bot的名称", max_length=255, verbose_name="Bot名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Bot的简介描述",
                        null=True,
                        verbose_name="Bot简介",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Bot头像图片，支持jpg、png、gif、webp格式，最大5MB",
                        null=True,
                        upload_to=bot.models.bot.avatar_upload_path,
                        verbose_name="Bot头像",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("collaborators", "仅协作者可访问"),
                            ("public", "所有用户可访问"),
                        ],
                        default="collaborators",
                        help_text="设置谁可以访问这个Bot",
                        max_length=20,
                        verbose_name="访问权限",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        help_text="用于URL的唯一标识符，如果为空则自动生成",
                        max_length=100,
                        unique=True,
                        verbose_name="Bot路径",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="是否启用该Bot", verbose_name="是否有效"
                    ),
                ),
                (
                    "assistant_id",
                    models.CharField(
                        blank=True,
                        help_text="LangGraph中对应的Assistant ID",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="LangGraph Assistant ID",
                    ),
                ),
                (
                    "graph_id",
                    models.CharField(
                        default="agent",
                        help_text="LangGraph的Graph ID",
                        max_length=255,
                        verbose_name="Graph ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_bots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot",
                "verbose_name_plural": "Bots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BotCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "管理权限"), ("readonly", "只读权限")],
                        default="readonly",
                        help_text="协作者在Bot中的权限级别",
                        max_length=20,
                        verbose_name="角色权限",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_bot_collaborators",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="添加者",
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborators",
                        to="bot.bot",
                        verbose_name="Bot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborating_bots",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="协作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot协作者",
                "verbose_name_plural": "Bot协作者",
                "ordering": ["-added_at"],
                "unique_together": {("bot", "user")},
            },
        ),
    ]
