# Generated by Django 5.2.4 on 2025-07-27 08:23

import django.db.models.deletion
import knowledge.models.namespace
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Namespace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="知识库的名称",
                        max_length=255,
                        verbose_name="知识库名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="知识库的简介描述",
                        null=True,
                        verbose_name="知识库简介",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        help_text="知识库封面图片，支持jpg、png、gif、webp格式，最大5MB",
                        null=True,
                        upload_to=knowledge.models.namespace.cover_upload_path,
                        verbose_name="知识库封面",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("collaborators", "仅协作者可访问"),
                            ("public", "所有用户可访问"),
                        ],
                        default="collaborators",
                        help_text="设置谁可以访问这个知识库",
                        max_length=20,
                        verbose_name="访问权限",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        help_text="用于URL的唯一标识符，如果为空则自动生成",
                        max_length=100,
                        unique=True,
                        verbose_name="知识库路径",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="是否启用该知识库",
                        verbose_name="是否有效",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_namespaces",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库",
                "verbose_name_plural": "知识库",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NamespaceCollaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_edit",
                    models.BooleanField(
                        default=True, help_text="是否有编辑权限", verbose_name="可编辑"
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_collaborators",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="添加者",
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborators",
                        to="knowledge.namespace",
                        verbose_name="知识库",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborating_namespaces",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="协作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库协作者",
                "verbose_name_plural": "知识库协作者",
                "ordering": ["-added_at"],
                "unique_together": {("namespace", "user")},
            },
        ),
    ]
