# Generated by Django 5.2.4 on 2025-07-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="namespacecollaborator",
            name="can_edit",
        ),
        migrations.AddField(
            model_name="namespacecollaborator",
            name="role",
            field=models.CharField(
                choices=[("admin", "管理权限"), ("readonly", "只读权限")],
                default="readonly",
                help_text="协作者在知识库中的权限级别",
                max_length=20,
                verbose_name="角色权限",
            ),
        ),
    ]
