# Generated by Django 5.2.4 on 2025-07-28 08:44

import django.db.models.deletion
import knowledge.models.knowledge_management
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_update_collaborator_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="知识分类的名称",
                        max_length=100,
                        verbose_name="分类名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="知识分类的详细描述",
                        null=True,
                        verbose_name="分类描述",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#1890ff",
                        help_text="用于前端显示的分类颜色，格式：#ffffff",
                        max_length=7,
                        verbose_name="分类颜色",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="数字越小排序越靠前",
                        verbose_name="排序序号",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="knowledge.namespace",
                        verbose_name="所属知识库",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识分类",
                "verbose_name_plural": "知识分类",
                "ordering": ["sort_order", "name"],
                "unique_together": {("namespace", "name")},
            },
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="知识文档或文件夹的标题",
                        max_length=255,
                        verbose_name="标题",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="知识文档的内容，支持Markdown格式",
                        null=True,
                        verbose_name="内容",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="知识文档的摘要描述",
                        null=True,
                        verbose_name="摘要",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("folder", "文件夹"), ("document", "文档")],
                        default="document",
                        help_text="文件夹或文档",
                        max_length=10,
                        verbose_name="文档类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="知识文档的附件文件",
                        null=True,
                        upload_to=knowledge.models.knowledge_management.knowledge_file_upload_path,
                        verbose_name="附件",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="在同级目录中的排序序号，数字越小排序越靠前",
                        verbose_name="排序序号",
                    ),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览次数")),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="是否对知识库内所有成员公开",
                        verbose_name="是否公开",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="knowledge.knowledgecategory",
                        verbose_name="分类",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "last_editor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edited_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="最后编辑者",
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="knowledge.namespace",
                        verbose_name="所属知识库",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="用于构建层次结构",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="knowledge.knowledgedocument",
                        verbose_name="父级文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识文档",
                "verbose_name_plural": "知识文档",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="评论内容")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评论者",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="用于回复功能",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="knowledge.knowledgecomment",
                        verbose_name="父评论",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="knowledge.knowledgedocument",
                        verbose_name="关联文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识评论",
                "verbose_name_plural": "知识评论",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="知识标签的名称",
                        max_length=50,
                        verbose_name="标签名称",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#f5f5f5",
                        help_text="用于前端显示的标签颜色，格式：#ffffff",
                        max_length=7,
                        verbose_name="标签颜色",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="标签被使用的次数", verbose_name="使用次数"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "namespace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="knowledge.namespace",
                        verbose_name="所属知识库",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识标签",
                "verbose_name_plural": "知识标签",
                "ordering": ["-usage_count", "name"],
                "unique_together": {("namespace", "name")},
            },
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="documents",
                to="knowledge.knowledgetag",
                verbose_name="标签",
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.CharField(
                        help_text="版本号，如：v1.0、v1.1等",
                        max_length=20,
                        verbose_name="版本号",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="摘要"),
                ),
                (
                    "change_log",
                    models.TextField(
                        blank=True,
                        help_text="记录此版本的变更内容",
                        null=True,
                        verbose_name="变更日志",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="knowledge.knowledgedocument",
                        verbose_name="关联文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识版本",
                "verbose_name_plural": "知识版本",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["namespace", "parent"], name="knowledge_k_namespa_3e29c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["namespace", "doc_type"], name="knowledge_k_namespa_dd863a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["created_at"], name="knowledge_k_created_67b925_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgeversion",
            unique_together={("document", "version_number")},
        ),
    ]
