# Generated by Django 5.2.4 on 2025-07-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0004_remove_unnecessary_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgedocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("folder", "文件夹"),
                    ("document", "文档"),
                    ("tool", "工具"),
                    ("form", "表单"),
                ],
                default="document",
                help_text="文件夹、文档、工具或表单",
                max_length=10,
                verbose_name="文档类型",
            ),
        ),
    ]
