# Generated by Django 5.2.4 on 2025-07-29 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0005_alter_knowledgedocument_doc_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="type_specific_data",
            field=models.JSONField(
                blank=True,
                help_text="存储不同知识类型的特定数据（工具配置、表单配置等）",
                null=True,
                verbose_name="类型特定数据",
            ),
        ),
        migrations.CreateModel(
            name="FormDataEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="用户提交的表单数据", verbose_name="表单数据"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "form_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_entries",
                        to="knowledge.knowledgedocument",
                        verbose_name="关联的表单知识",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交者",
                    ),
                ),
            ],
            options={
                "verbose_name": "表单数据条目",
                "verbose_name_plural": "表单数据条目",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["form_document", "created_at"],
                        name="knowledge_f_form_do_8b117a_idx",
                    ),
                    models.Index(
                        fields=["submitter", "created_at"],
                        name="knowledge_f_submitt_679911_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ToolExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        help_text="工具执行时的输入参数", verbose_name="输入数据"
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True,
                        help_text="工具执行的结果",
                        null=True,
                        verbose_name="输出数据",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="执行失败时的错误信息",
                        null=True,
                        verbose_name="错误信息",
                    ),
                ),
                (
                    "execution_time",
                    models.DurationField(
                        blank=True,
                        help_text="工具实际执行时长",
                        null=True,
                        verbose_name="执行时长",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行者",
                    ),
                ),
                (
                    "tool_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_executions",
                        to="knowledge.knowledgedocument",
                        verbose_name="关联的工具知识",
                    ),
                ),
            ],
            options={
                "verbose_name": "工具执行记录",
                "verbose_name_plural": "工具执行记录",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tool_document", "status"],
                        name="knowledge_t_tool_do_e26c76_idx",
                    ),
                    models.Index(
                        fields=["executor", "created_at"],
                        name="knowledge_t_executo_3f3494_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="knowledge_t_status_dc59fb_idx",
                    ),
                ],
            },
        ),
    ]
