# Generated by Django 5.2.4 on 2025-08-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "knowledge",
            "0006_knowledgedocument_type_specific_data_formdataentry_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="markdown_content",
            field=models.TextField(
                blank=True,
                help_text="知识文档的Markdown格式内容，用于向量存储",
                null=True,
                verbose_name="Markdown内容",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="知识文档的HTML内容",
                null=True,
                verbose_name="内容",
            ),
        ),
    ]
