# Generated by Django 5.2.4 on 2025-07-26 09:01

import user.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="用户头像，支持jpg、png、gif、webp格式，最大5MB",
                null=True,
                upload_to=user.models.user.avatar_upload_path,
                verbose_name="头像",
            ),
        ),
    ]
