# Generated by Django 5.2.4 on 2025-07-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="生日"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("unknown", "未知"), ("male", "男性"), ("female", "女性")],
                default="unknown",
                max_length=10,
                verbose_name="性别",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="登录被锁定"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "普通用户"), ("admin", "管理员")],
                default="user",
                max_length=10,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否有效"),
        ),
    ]
