# Generated by Django 5.2.4 on 2025-07-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_customuser_options_customuser_birthday_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "用户", "verbose_name_plural": "用户"},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_locked",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("male", "男性"), ("female", "女性"), ("unknown", "未知")],
                default="unknown",
                max_length=10,
                verbose_name="性别",
            ),
        ),
    ]
