# Generated by Django 5.2.4 on 2025-08-10 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0, help_text='平台注册用户总数', verbose_name='总用户数')),
                ('active_users', models.IntegerField(default=0, help_text='近30天活跃用户数', verbose_name='活跃用户数')),
                ('total_llm_models', models.IntegerField(default=0, help_text='平台接入的大模型总数', verbose_name='大模型总数')),
                ('total_namespaces', models.IntegerField(default=0, help_text='平台知识库总数', verbose_name='知识库总数')),
                ('total_documents', models.IntegerField(default=0, help_text='平台文档总数', verbose_name='文档总数')),
                ('total_bots', models.IntegerField(default=0, help_text='平台机器人总数', verbose_name='机器人总数')),
                ('date', models.DateField(help_text='统计数据对应的日期', verbose_name='统计日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '平台统计',
                'verbose_name_plural': '平台统计',
                'db_table': 'summary_platform_summary',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='summary_date_idx'), models.Index(fields=['created_at'], name='summary_created_idx')],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='UserSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_llm_models', models.IntegerField(default=0, help_text='平台接入的大模型总数量', verbose_name='接入大模型数量')),
                ('total_namespaces', models.IntegerField(default=0, help_text='当前用户可访问的知识库数量', verbose_name='知识库数量')),
                ('created_namespaces', models.IntegerField(default=0, help_text='当前用户创建的知识库数量', verbose_name='创建的知识库数量')),
                ('collaborated_namespaces', models.IntegerField(default=0, help_text='当前用户被邀请协作的知识库数量', verbose_name='协作知识库数量')),
                ('total_documents', models.IntegerField(default=0, help_text='当前用户创建的文档总数', verbose_name='文档总数')),
                ('normal_documents', models.IntegerField(default=0, help_text='当前用户创建的普通文档数量', verbose_name='普通文档数量')),
                ('tool_documents', models.IntegerField(default=0, help_text='当前用户创建的工具文档数量', verbose_name='工具文档数量')),
                ('created_bots', models.IntegerField(default=0, help_text='当前用户创建的机器人数量', verbose_name='创建的机器人数量')),
                ('collaborated_bots', models.IntegerField(default=0, help_text='当前用户被邀请协作的机器人数量', verbose_name='协作机器人数量')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(help_text='关联的用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户统计',
                'verbose_name_plural': '用户统计',
                'db_table': 'summary_user_summary',
                'indexes': [models.Index(fields=['user'], name='summary_user_idx'), models.Index(fields=['last_updated'], name='summary_updated_idx')],
            },
        ),
    ]
