apiVersion: v1
kind: Service
metadata:
  name: langgraph-redis
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: langgraph-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: langgraph-postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: langgraph-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: langgraph-api
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: langgraph-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: {{ .Values.application.node_port }}