/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryTree: typeof import('./src/components/CategoryTree.vue')['default']
    DatabaseEditor: typeof import('./src/components/DatabaseEditor.vue')['default']
    Demo: typeof import('./src/components/Demo.vue')['default']
    DirectoryItem: typeof import('./src/components/DirectoryItem.vue')['default']
    DirectoryNode: typeof import('./src/components/DirectoryNode.vue')['default']
    DirectoryTree: typeof import('./src/components/DirectoryTree.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListNumber: typeof import('./src/components/ListNumber.vue')['default']
    MoveDialog: typeof import('./src/components/MoveDialog.vue')['default']
    MyForm: typeof import('./src/components/MyForm.vue')['default']
    MyLayout: typeof import('./src/components/MyLayout.vue')['default']
    MyMarkdown: typeof import('./src/components/MyMarkdown.vue')['default']
    NamespaceManager: typeof import('./src/components/NamespaceManager.vue')['default']
    NewEditor: typeof import('./src/components/NewEditor.vue')['default']
    NoteDemo: typeof import('./src/components/NoteDemo.vue')['default']
    NoteEditor: typeof import('./src/components/NoteEditor.vue')['default']
    NoteList: typeof import('./src/components/NoteList.vue')['default']
    NoteTypeSelector: typeof import('./src/components/NoteTypeSelector.vue')['default']
    ProviderA: typeof import('./src/components/ProviderA.vue')['default']
    ProviderB: typeof import('./src/components/ProviderB.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolEditor: typeof import('./src/components/ToolEditor.vue')['default']
    TreeNode: typeof import('./src/components/TreeNode.vue')['default']
    TreeStructure: typeof import('./src/components/TreeStructure.vue')['default']
    WorkspaceView: typeof import('./src/components/WorkspaceView.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
